update cargo config and add sccache installation script

diff --git a/lcdot b/lcdot
--- a/lcdot
+++ b/lcdot
@@ -55,6 +55,7 @@ lcdot_usage() {
   printf "  %s   install my own vim configuration\n" "vim     "
   printf "  %s   install my own wezterm configuration\n" "wezterm "
   printf "  %s   install my own zshell configuration\n" "zsh     "
+  printf "  %s   Configure cargo package manager to use sccache\n" "sccache "
   printf "  %s   installs all configuration files. Backup option is enabled by default\n" "all     "
   echo
 
@@ -898,6 +899,46 @@ lcdot_zsh_usage() {
 }
 
 # :command.usage
+lcdot_sccache_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lcdot sccache - Configure cargo package manager to use sccache\n"
+    echo
+
+  else
+    printf "lcdot sccache - Configure cargo package manager to use sccache\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lcdot sccache [OPTIONS]\n"
+  printf "  lcdot sccache --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--backup, -b"
+    printf "    Backup existing configurations in LCDOT_BACKUP/cargo\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--install, -i"
+    printf "    Install sccache as well as set up cargo configuration\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 lcdot_all_usage() {
   if [[ -n $long_usage ]]; then
     printf "lcdot all - installs all configuration files. Backup option is enabled by default\n"
@@ -1437,6 +1478,31 @@ lcdot_zsh_command() {
 }
 
 # :command.function
+lcdot_sccache_command() {
+  # src/sccache_command.sh
+  install=${args[--install]}
+  backup=${args[--backup]}
+  DOTFILES_LOCATION=$PWD
+
+  if [ "$install" ]; then
+      echo "Installing sccache"
+      cargo install sccache --locked
+  fi
+
+  if [ "$backup" ]; then
+      echo "Moving previous configuration in $LCDOT_BACKUP/cargo"
+      mkdir -p "$LCDOT_BACKUP"/cargo
+
+      mv "$HOME"/.cargo/config.toml "$LCDOT_BACKUP"/cargo/
+  fi
+
+  echo "Setting up cargo to use sccache"
+  ln -sf "$DOTFILES_LOCATION"/cargo/config.toml "$HOME"/.cargo/config.toml
+  echo "Done"
+
+}
+
+# :command.function
 lcdot_all_command() {
   # src/all_command.sh
   echo "This command is not implemented yet, feel free to open an issue on the GitHub page"
@@ -1620,6 +1686,13 @@ parse_requirements() {
       action="zsh"
       shift
       lcdot_zsh_parse_requirements "$@"
+      shift $#
+      ;;
+
+    sccache)
+      action="sccache"
+      shift
+      lcdot_sccache_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2938,6 +3011,74 @@ lcdot_zsh_parse_requirements() {
 }
 
 # :command.parse_requirements
+lcdot_sccache_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lcdot_sccache_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v cargo >/dev/null 2>&1; then
+    deps['rust']="$(command -v cargo | head -n1)"
+  else
+    printf "missing dependency: rust\n" >&2
+    printf "%s\n" "go to https://doc.rust-lang.org/cargo/getting-started/installation.html to install cargo and rust" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="sccache"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --backup | -b)
+
+        # :flag.case_no_arg
+        args['--backup']=1
+        shift
+        ;;
+
+      # :flag.case
+      --install | -i)
+
+        # :flag.case_no_arg
+        args['--install']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 lcdot_all_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -3023,6 +3164,7 @@ run() {
     "vim") lcdot_vim_command ;;
     "wezterm") lcdot_wezterm_command ;;
     "zsh") lcdot_zsh_command ;;
+    "sccache") lcdot_sccache_command ;;
     "all") lcdot_all_command ;;
   esac
 }
