update bashly, add procs config and installation script

diff --git a/lcdot b/lcdot
--- a/lcdot
+++ b/lcdot
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.7 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -59,6 +59,7 @@ lcdot_usage() {
   printf "  %s   Install my own alacritty configuration\n" "alacritty"
   printf "  %s   Install fzf aliases\n" "fzf      "
   printf "  %s   installs all configuration files\n" "all      "
+  printf "  %s   Install my procs configuration\n" "procs    "
   echo
 
   # :command.long_usage
@@ -85,6 +86,7 @@ lcdot_usage() {
     # :environment_variable.usage
     printf "  %s\n" "ARCHBTW"
     printf "    whether or not installing to a ARCH based distro. Tries to install tools\n    from AUR packages\n"
+    printf "    Default: false\n"
     echo
 
   fi
@@ -1060,6 +1062,46 @@ lcdot_all_usage() {
   fi
 }
 
+# :command.usage
+lcdot_procs_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lcdot procs - Install my procs configuration\n"
+    echo
+
+  else
+    printf "lcdot procs - Install my procs configuration\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lcdot procs [OPTIONS]\n"
+  printf "  lcdot procs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--backup, -b"
+    printf "    Backup existing configurations in LCDOT_BACKUP/procs\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--install, -i"
+    printf "    Install the tool itself as well as its configuration\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -1458,6 +1500,36 @@ install_porsmo() {
     echo "There is no configuration to install for porsmo, congrats!"
 }
 
+# src/lib/procs.sh
+install_procs() {
+	backup=${args[--backup]}
+	install=${args[--install]}
+	DOTFILES_LOCATION=$PWD
+	if [ "$install" ]; then
+		echo "Installing procs"
+
+		if [ "$ARCHBTW"=true ]; then
+			echo "Arch based distro detected, installing using pacman"
+			sudo pacman -S procs
+
+		else
+			echo "Installing procs with cargo"
+			cargo install procs
+		fi
+	fi
+	echo "Installing procs configuration from $DOTFILES_LOCATION"
+	mkdir -p "$HOME"/.config/procs
+	if [ "$backup" ]; then
+		echo "Moving previous configurations in $LCDOT_BACKUP/procs"
+		mkdir -p "$LCDOT_BACKUP"/procs
+
+		mv "$HOME"/.config/procs/* "$LCDOT_BACKUP"/procs/
+	fi
+
+	echo "Setting up procs configuration"
+	ln -sf "$DOTFILES_LOCATION"/procs/config.toml "$HOME"/.config/procs/config.toml
+}
+
 # src/lib/rtx.sh
 install_rtx() {
     install=${args[--install]}
@@ -1844,9 +1916,18 @@ lcdot_all_command() {
   	install_zsh
 
   	install_fzf
+
+  	install_procs
   }
 
   install_all
+
+}
+
+# :command.function
+lcdot_procs_command() {
+  # src/procs_command.sh
+  install_procs
 
 }
 
@@ -1876,6 +1957,7 @@ parse_requirements() {
   # :command.environment_variables_filter
   # :command.environment_variables_default
   export LCDOT_BACKUP="${LCDOT_BACKUP:-$HOME/lcdot_backup}"
+  export ARCHBTW="${ARCHBTW:-false}"
 
   # :command.command_filter
   action=${1:-}
@@ -2055,6 +2137,13 @@ parse_requirements() {
       action="all"
       shift
       lcdot_all_parse_requirements "$@"
+      shift $#
+      ;;
+
+    procs)
+      action="procs"
+      shift
+      lcdot_procs_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2688,7 +2777,7 @@ lcdot_lazygit_parse_requirements() {
     deps['rust']="$(command -v go | head -n1)"
   else
     printf "missing dependency: rust\n" >&2
-    printf "%s\n" "go to https://go.dev/doc/install to install go lang, or use managers such as rtx" >&2
+    printf "%s\n" "go to https://go.dev/doc/install to install go lang, or use runtime managers such as rtx" >&2
     exit 1
   fi
 
@@ -3619,6 +3708,74 @@ lcdot_all_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+lcdot_procs_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lcdot_procs_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v cargo >/dev/null 2>&1; then
+    deps['rust']="$(command -v cargo | head -n1)"
+  else
+    printf "missing dependency: rust\n" >&2
+    printf "%s\n" "go to https://doc.rust-lang.org/cargo/getting-started/installation.html to install cargo and rust" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="procs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --backup | -b)
+
+        # :flag.case_no_arg
+        args['--backup']=1
+        shift
+        ;;
+
+      # :flag.case
+      --install | -i)
+
+        # :flag.case_no_arg
+        args['--install']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.3.0"
@@ -3627,6 +3784,7 @@ initialize() {
 
   # :command.environment_variables_default
   export LCDOT_BACKUP="${LCDOT_BACKUP:-$HOME/lcdot_backup}"
+  export ARCHBTW="${ARCHBTW:-false}"
 
 }
 
@@ -3665,6 +3823,7 @@ run() {
     "alacritty") lcdot_alacritty_command ;;
     "fzf") lcdot_fzf_command ;;
     "all") lcdot_all_command ;;
+    "procs") lcdot_procs_command ;;
   esac
 }
 
