add alacritty command and add bat theme

diff --git a/lcdot b/lcdot
--- a/lcdot
+++ b/lcdot
@@ -34,29 +34,30 @@ lcdot_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   install my own nvim configuration\n" "nvim    "
-  printf "  %s   Install my starship prompt\n" "starship"
-  printf "  %s   Install the delta diff pager for git\n" "delta   "
-  printf "  %s   Install the exa listing tool\n" "exa     "
-  printf "  %s   Install the bat cli tool\n" "bat     "
-  printf "  %s   Install the bob-nvim cli tool\n" "bob-nvim"
-  printf "  %s   Install the zellij cli tool\n" "zellij  "
-  printf "  %s   Install the mprocs cli tool\n" "mprocs  "
-  printf "  %s   Install the gitui cli tool\n" "gitui   "
-  printf "  %s   Install the lazygit cli tool\n" "lazygit "
-  printf "  %s   Install the porsmo cli tool\n" "porsmo  "
-  printf "  %s   Install the wiki-tui cli tool\n" "wiki-tui"
-  printf "  %s   Install the fd-find cli tool\n" "fd-find "
-  printf "  %s   Install the zoxide cli tool\n" "zoxide  "
-  printf "  %s   Install the rtx-cli cli tool\n" "rtx-cli "
-  printf "  %s   Install the navi cli tool\n" "navi    "
-  printf "  %s   install my own tmux configuration\n" "tmux    "
-  printf "  %s   Install the ncspot cli tool\n" "ncspot  "
-  printf "  %s   install my own vim configuration\n" "vim     "
-  printf "  %s   install my own wezterm configuration\n" "wezterm "
-  printf "  %s   install my own zshell configuration\n" "zsh     "
-  printf "  %s   Configure cargo package manager to use sccache\n" "sccache "
-  printf "  %s   installs all configuration files\n" "all     "
+  printf "  %s   install my own nvim configuration\n" "nvim     "
+  printf "  %s   Install my starship prompt\n" "starship "
+  printf "  %s   Install the delta diff pager for git\n" "delta    "
+  printf "  %s   Install the exa listing tool\n" "exa      "
+  printf "  %s   Install the bat cli tool\n" "bat      "
+  printf "  %s   Install the bob-nvim cli tool\n" "bob-nvim "
+  printf "  %s   Install the zellij cli tool\n" "zellij   "
+  printf "  %s   Install the mprocs cli tool\n" "mprocs   "
+  printf "  %s   Install the gitui cli tool\n" "gitui    "
+  printf "  %s   Install the lazygit cli tool\n" "lazygit  "
+  printf "  %s   Install the porsmo cli tool\n" "porsmo   "
+  printf "  %s   Install the wiki-tui cli tool\n" "wiki-tui "
+  printf "  %s   Install the fd-find cli tool\n" "fd-find  "
+  printf "  %s   Install the zoxide cli tool\n" "zoxide   "
+  printf "  %s   Install the rtx-cli cli tool\n" "rtx-cli  "
+  printf "  %s   Install the navi cli tool\n" "navi     "
+  printf "  %s   install my own tmux configuration\n" "tmux     "
+  printf "  %s   Install the ncspot cli tool\n" "ncspot   "
+  printf "  %s   install my own vim configuration\n" "vim      "
+  printf "  %s   install my own wezterm configuration\n" "wezterm  "
+  printf "  %s   install my own zshell configuration\n" "zsh      "
+  printf "  %s   Configure cargo package manager to use sccache\n" "sccache  "
+  printf "  %s   Install my own alacritty configuration\n" "alacritty"
+  printf "  %s   installs all configuration files\n" "all      "
   echo
 
   # :command.long_usage
@@ -944,6 +945,46 @@ lcdot_sccache_usage() {
 }
 
 # :command.usage
+lcdot_alacritty_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lcdot alacritty - Install my own alacritty configuration\n"
+    echo
+
+  else
+    printf "lcdot alacritty - Install my own alacritty configuration\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lcdot alacritty [OPTIONS]\n"
+  printf "  lcdot alacritty --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--backup, -b"
+    printf "    Backup existing configurations in LCDOT_BACKUP/alacritty\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--install, -i"
+    printf "    Install alacritty as well as set up its configuration\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 lcdot_all_usage() {
   if [[ -n $long_usage ]]; then
     printf "lcdot all - installs all configuration files\n"
@@ -1036,6 +1077,41 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/alacritty.sh
+install_alacritty() {
+
+    local backup=${args[--backup]}
+    local install=${args[--install]}
+    local DOTFILES_LOCATION=$PWD
+    if [ "$install" ]; then
+        echo "Installing alacritty"
+
+        echo "Installing dependencies"
+        if [ "$ARCHBTW"=true ]; then
+            echo "Arch based distro detected, installing using pacman"
+            pacman -S cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python
+
+        else
+            sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
+        fi
+
+        echo "Installing alacritty from source with cargo"
+        cargo install alacritty
+    fi
+    echo "Installing  alacritty configuration from $DOTFILES_LOCATION"
+    mkdir -p "$HOME/.config/alacritty"
+    if [ "$backup" ]; then
+        echo "Moving previous configurations in $LCDOT_BACKUP/alacritty"
+        mkdir -p "$LCDOT_BACKUP"/alacritty
+
+        mv "$HOME/.config/alacritty/*.toml" "$LCDOT_BACKUP"/alacritty/
+    fi
+
+    echo "Setting up alacritty configuration"
+    ln -s "$DOTFILES_LOCATION/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
+    ln -s "$DOTFILES_LOCATION/alacritty/tokyonight-storm.toml" "$HOME/.config/alacritty/tokyonight-storm.toml"
+}
+
 # src/lib/bat.sh
 install_bat() {
     local backup=${args[--backup]}
@@ -1064,7 +1140,8 @@ install_bat() {
     fi
 
     echo "Setting up bat configuration"
-    ln -sf "$DOTFILES_LOCATION"/bat/config "$bat_config_file"
+    ln -sf "$DOTFILES_LOCATION/bat/config" "$(bat --config-file)"
+    ln -sfn "$DOTFILES_LOCATION/bat/themes/" "$(bat --config-dir)"
 }
 
 # src/lib/bob.sh
@@ -1651,6 +1728,13 @@ lcdot_sccache_command() {
 }
 
 # :command.function
+lcdot_alacritty_command() {
+  # src/alacritty_command.sh
+  install_alacritty
+
+}
+
+# :command.function
 lcdot_all_command() {
   # src/all_command.sh
   install_all() {
@@ -1884,6 +1968,13 @@ parse_requirements() {
       action="sccache"
       shift
       lcdot_sccache_parse_requirements "$@"
+      shift $#
+      ;;
+
+    alacritty)
+      action="alacritty"
+      shift
+      lcdot_alacritty_parse_requirements "$@"
       shift $#
       ;;
 
@@ -3278,6 +3369,74 @@ lcdot_sccache_parse_requirements() {
 }
 
 # :command.parse_requirements
+lcdot_alacritty_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lcdot_alacritty_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v cargo >/dev/null 2>&1; then
+    deps['rust']="$(command -v cargo | head -n1)"
+  else
+    printf "missing dependency: rust\n" >&2
+    printf "%s\n" "go to https://doc.rust-lang.org/cargo/getting-started/installation.html to install cargo and rust" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="alacritty"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --backup | -b)
+
+        # :flag.case_no_arg
+        args['--backup']=1
+        shift
+        ;;
+
+      # :flag.case
+      --install | -i)
+
+        # :flag.case_no_arg
+        args['--install']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 lcdot_all_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -3379,6 +3538,7 @@ run() {
     "wezterm") lcdot_wezterm_command ;;
     "zsh") lcdot_zsh_command ;;
     "sccache") lcdot_sccache_command ;;
+    "alacritty") lcdot_alacritty_command ;;
     "all") lcdot_all_command ;;
   esac
 }
