add ncspot installation and configuration

diff --git a/lcdot b/lcdot
--- a/lcdot
+++ b/lcdot
@@ -51,6 +51,7 @@ lcdot_usage() {
   printf "  %s   Install the rtx-cli cli tool\n" "rtx-cli "
   printf "  %s   Install the navi cli tool\n" "navi    "
   printf "  %s   install my own tmux configuration\n" "tmux    "
+  printf "  %s   Install the ncspot cli tool\n" "ncspot  "
   printf "  %s   install my own vim configuration\n" "vim     "
   printf "  %s   install my own wezterm configuration\n" "wezterm "
   printf "  %s   install my own zshell configuration\n" "zsh     "
@@ -527,8 +528,8 @@ lcdot_wiki_tui_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "--backup, -b"
-    printf "    Backup existing configurations in LCDOT_BACKUP/wiki-tui\n"
+    printf "  %s\n" "--install, -i"
+    printf "    Install the tool itself as well as its configuration\n"
     echo
 
     # :command.usage_fixed_flags
@@ -722,6 +723,46 @@ lcdot_tmux_usage() {
     # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  lcodt tmux -b\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+lcdot_ncspot_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lcdot ncspot - Install the ncspot cli tool\n"
+    echo
+
+  else
+    printf "lcdot ncspot - Install the ncspot cli tool\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lcdot ncspot [OPTIONS]\n"
+  printf "  lcdot ncspot --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--backup, -b"
+    printf "    Backup existing configurations in LCDOT_BACKUP/ncspot\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--install, -i"
+    printf "    Install the tool itself as well as its configuration\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -1210,10 +1251,14 @@ lcdot_porsmo_command() {
 # :command.function
 lcdot_wiki_tui_command() {
   # src/wiki_tui_command.sh
-  echo "# this file is located in 'src/wiki_tui_command.sh'"
-  echo "# code for 'lcdot wiki-tui' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  install=${args[--install]}
+  DOTFILES_LOCATION=$PWD
+  if [ "$install" ]; then
+      echo "Installing wiki-tui"
+      cargo install wiki-tui
+  fi
+
+  echo "There is no configuration to install for wiki-tui, congrats!"
 
 }
 
@@ -1314,6 +1359,31 @@ lcdot_tmux_command() {
   echo "Installing TPM"
   git clone https://github.com/tmux-plugins/tpm "$HOME/.config/tmux/plugins/tpm"
   echo "Done, open tmux and press CTRL I to install plugins"
+
+}
+
+# :command.function
+lcdot_ncspot_command() {
+  # src/ncspot_command.sh
+  install=${args[--install]}
+  backup=${args[--backup]}
+  DOTFILES_LOCATION=$PWD
+
+  if [ "$install" ]; then
+      echo "Installing ncspot"
+      cargo install ncspot --locked
+  fi
+
+  if [ "$backup" ]; then
+      echo "Moving previous configurations in $LCDOT_BACKUP/ncspot"
+      mkdir -p "$LCDOT_BACKUP"/rust-tools/ncspot
+
+      mv "$HOME"/.config/ncspot "$LCDOT_BACKUP"/rust-tools/ncspot
+  fi
+
+  echo "Setting up ncspot configuration"
+  ln -sfn "$DOTFILES_LOCATION/ncspot/" "$HOME/.config/ncspot"
+  echo "Done"
 
 }
 
@@ -1522,6 +1592,13 @@ parse_requirements() {
       action="tmux"
       shift
       lcdot_tmux_parse_requirements "$@"
+      shift $#
+      ;;
+
+    ncspot)
+      action="ncspot"
+      shift
+      lcdot_ncspot_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2315,10 +2392,10 @@ lcdot_wiki_tui_parse_requirements() {
     key="$1"
     case "$key" in
       # :flag.case
-      --backup | -b)
+      --install | -i)
 
         # :flag.case_no_arg
-        args['--backup']=1
+        args['--install']=1
         shift
         ;;
 
@@ -2640,6 +2717,74 @@ lcdot_tmux_parse_requirements() {
 }
 
 # :command.parse_requirements
+lcdot_ncspot_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lcdot_ncspot_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v cargo >/dev/null 2>&1; then
+    deps['rust']="$(command -v cargo | head -n1)"
+  else
+    printf "missing dependency: rust\n" >&2
+    printf "%s\n" "go to https://doc.rust-lang.org/cargo/getting-started/installation.html to install cargo and rust" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="ncspot"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --backup | -b)
+
+        # :flag.case_no_arg
+        args['--backup']=1
+        shift
+        ;;
+
+      # :flag.case
+      --install | -i)
+
+        # :flag.case_no_arg
+        args['--install']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 lcdot_vim_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -2874,6 +3019,7 @@ run() {
     "rtx-cli") lcdot_rtx_cli_command ;;
     "navi") lcdot_navi_command ;;
     "tmux") lcdot_tmux_command ;;
+    "ncspot") lcdot_ncspot_command ;;
     "vim") lcdot_vim_command ;;
     "wezterm") lcdot_wezterm_command ;;
     "zsh") lcdot_zsh_command ;;
